name = "GeometricEquations"
uuid = "c85262ba-a08a-430a-b926-d29770767bf2"
authors = ["Michael Kraus"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
